# Change these first
owner: drsumaiya # Your GitHub organization or username, where this repository lives
repo: drsumaiya.com-upptime # The name of this repository

sites:
  - name: DrSumaiya.com
    url: https://DrSumaiya.com
  - name: DrSumaiya - Inquiry Form
    url: https://drsumaiya.com/inquiry-form/
  - name: DrSumaiya - Booking Form
    url: https://drsumaiya.com/form/
  - name: DrSumaiya - Success Stories Post
    url: https://drsumaiya.com/post/transforming-health-and-lives-real-success-stories-from-dr-sumaiyas-nutricare-clinic/
  - name: IQS
    url: https://iqs.org.in
  - name: IQS - Islamic Courses
    url: https://iqs.org.in/islamic-courses/
  - name: IQS - Admissions & Inquiry
    url: https://iqs.org.in/inquiry/
  - name: IQS - Sidr Leaves Remedy Post
    url: https://iqs.org.in/the-ancient-islamic-remedy-of-sidr-leaves-for-protection-against-black-magic-and-evil-eye/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.drsumaiya.com
  # baseUrl: /drsumaiya.com-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  scripts:
    - src: /pagespeed.js
      async: true
  links:
    - rel: stylesheet
      href: https://status.drsumaiya.com/pagespeed.css
  navbar:
    - title: Status
      href: /
    - title: Performance
      href: "#pagespeed-section"
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
